#pragma once
// ---------------------------------------------------------------------------
// PHI v2 — backend / device / registry interface (ggml multi-backend analogue).
//
// This is the heart of the ggml/llama.cpp-style runtime multi-backend layer:
//   * BackendI       ~ ggml_backend_i        (dispatch / plan / event / sync)
//   * DeviceI        ~ ggml_backend_device_i (enumerate buffers + op support)
//   * RegistryEntryI ~ ggml_backend_reg_i    (one registered backend provider)
//
// All physics kernels become backend op implementations in M3+. This milestone
// (M1) ships ONLY the layer + a smoke gate; no real op is wired yet.
//
// Opaque-handle design: Backend / Device / RegistryEntry / Plan / Event are
// opaque structs whose definitions live in the backend implementation. Each
// concrete definition begins with `const <Iface>* iface;` so the free-function
// wrappers below can dispatch through the vtable without seeing CUDA types.
//
// ModelView / DataView are forward-declared ONLY here — they are GENERATED by
// the nk codegen in M3 and describe the world's structural / mutable state that
// ops read & write. In M1 nothing dereferences them.
//
// PURE C++ — zero CUDA types. No STL in the public surface.
// ---------------------------------------------------------------------------

#include <cstddef>
#include <cstdint>

#include "phi/op_schema.hpp"
#include "phi/buffer.hpp"   // BufferType
#include "phi/plan.hpp"     // Plan
#include "phi/event.hpp"    // Event

namespace nuka::phi {

// --- Opaque handles ------------------------------------------------------
struct Backend;
struct Device;
struct RegistryEntry;

// Generated in M3 (nk codegen); phi only FORWARD-DECLARES them. Ops never
// dereference them in M1.
struct ModelView;
struct DataView;

// --- Status --------------------------------------------------------------
enum class Status : uint8_t { Ok, Unsupported, Failed, OutOfMemory };

// --- OpCall --------------------------------------------------------------
// One unit of work: an op id + a pointer to that op's POD params (op_schema.hpp).
// `params` lifetime is the owning Pipeline (the caller keeps it alive across
// plan capture + execution).
struct OpCall {
    NkOp        op;
    const void* params;
};

// ---------------------------------------------------------------------------
// BackendI — ggml_backend_i analogue.
// ---------------------------------------------------------------------------
struct BackendI {
    const char* (*get_name)(Backend*);
    void        (*free)(Backend*);
    Status      (*dispatch)(Backend*, const ModelView&, const DataView&, const OpCall&);
    void        (*synchronize)(Backend*);
    Plan*       (*plan_create)(Backend*, const ModelView&, const DataView&, const OpCall* calls, int n_calls);
    Status      (*plan_execute)(Backend*, Plan*);
    void        (*plan_free)(Backend*, Plan*);
    Event*      (*event_new)(Backend*);
    void        (*event_record)(Backend*, Event*);
    void        (*event_wait)(Backend*, Event*);
    void        (*event_free)(Backend*, Event*);
};

// ---------------------------------------------------------------------------
// DeviceI — ggml_backend_device_i analogue.
// ---------------------------------------------------------------------------
struct DeviceI {
    const char* (*get_name)(Device*);
    void        (*get_memory)(Device*, size_t* free_b, size_t* total_b);
    Backend*    (*init_backend)(Device*, const char* params_json);
    BufferType* (*get_buffer_type)(Device*);
    BufferType* (*get_host_buffer_type)(Device*);
    bool        (*supports_op)(Device*, NkOp);
};

// ---------------------------------------------------------------------------
// RegistryEntryI — ggml_backend_reg_i analogue. One per backend provider.
// ---------------------------------------------------------------------------
struct RegistryEntryI {
    const char* (*get_name)(RegistryEntry*);
    size_t      (*device_count)(RegistryEntry*);
    Device*     (*get_device)(RegistryEntry*, size_t i);
    void*       (*get_proc_address)(RegistryEntry*, const char* name); // optional extension point
};

// Opaque-handle layout contract: every concrete handle begins with its iface
// pointer. The wrappers reinterpret the handle as the matching head.
struct BackendHead       { const BackendI*       iface; };
struct DeviceHead        { const DeviceI*        iface; };
struct RegistryEntryHead { const RegistryEntryI* iface; };

inline const BackendI*       IfaceOf(Backend* b)       { return reinterpret_cast<const BackendHead*>(b)->iface; }
inline const DeviceI*        IfaceOf(Device* d)        { return reinterpret_cast<const DeviceHead*>(d)->iface; }
inline const RegistryEntryI* IfaceOf(RegistryEntry* r) { return reinterpret_cast<const RegistryEntryHead*>(r)->iface; }

// --- Backend convenience wrappers ---------------------------------------
inline const char* BackendName(Backend* b) { return IfaceOf(b)->get_name(b); }
inline void        BackendFree(Backend* b) { IfaceOf(b)->free(b); }
inline Status      BackendDispatch(Backend* b, const ModelView& m, const DataView& d, const OpCall& call) {
    return IfaceOf(b)->dispatch(b, m, d, call);
}
inline void        BackendSynchronize(Backend* b) { IfaceOf(b)->synchronize(b); }
inline Plan*       BackendPlanCreate(Backend* b, const ModelView& m, const DataView& d, const OpCall* calls, int n_calls) {
    return IfaceOf(b)->plan_create(b, m, d, calls, n_calls);
}
inline Status      BackendPlanExecute(Backend* b, Plan* p) { return IfaceOf(b)->plan_execute(b, p); }
inline void        BackendPlanFree(Backend* b, Plan* p)    { IfaceOf(b)->plan_free(b, p); }
inline Event*      BackendEventNew(Backend* b)             { return IfaceOf(b)->event_new(b); }
inline void        BackendEventRecord(Backend* b, Event* e) { IfaceOf(b)->event_record(b, e); }
inline void        BackendEventWait(Backend* b, Event* e)   { IfaceOf(b)->event_wait(b, e); }
inline void        BackendEventFree(Backend* b, Event* e)   { IfaceOf(b)->event_free(b, e); }

// --- Device convenience wrappers ----------------------------------------
inline const char* DeviceName(Device* d) { return IfaceOf(d)->get_name(d); }
inline void        DeviceGetMemory(Device* d, size_t* free_b, size_t* total_b) { IfaceOf(d)->get_memory(d, free_b, total_b); }
inline Backend*    DeviceInitBackend(Device* d, const char* params_json) { return IfaceOf(d)->init_backend(d, params_json); }
inline BufferType* DeviceBufferType(Device* d)     { return IfaceOf(d)->get_buffer_type(d); }
inline BufferType* DeviceHostBufferType(Device* d) { return IfaceOf(d)->get_host_buffer_type(d); }
inline bool        DeviceSupportsOp(Device* d, NkOp op) { return IfaceOf(d)->supports_op(d, op); }

// --- RegistryEntry convenience wrappers ---------------------------------
inline const char* RegistryEntryName(RegistryEntry* r) { return IfaceOf(r)->get_name(r); }
inline size_t      RegistryEntryDeviceCount(RegistryEntry* r) { return IfaceOf(r)->device_count(r); }
inline Device*     RegistryEntryGetDevice(RegistryEntry* r, size_t i) { return IfaceOf(r)->get_device(r, i); }
inline void*       RegistryEntryGetProcAddress(RegistryEntry* r, const char* name) { return IfaceOf(r)->get_proc_address(r, name); }

// ---------------------------------------------------------------------------
// Global registry (phi/registry.cpp).
// ---------------------------------------------------------------------------
void           RegisterBackend(RegistryEntry*);
size_t         BackendCount();
RegistryEntry* GetBackend(size_t i);

// Pick & init the best device's backend. This period: the first CUDA device.
// Returns nullptr if no backend/device is available.
Device*        InitBestDevice();

// --- Backend-bound buffer types (impl in the backend; CUDA-free here) -----
// The buffer types whose transfers run on the backend's MAIN stream. Use these
// when a consumer's kernels/ops run on backend->main (e.g. the diffsim op path),
// so transfers and compute share one stream. Contrast DeviceBufferType(device),
// which returns the device-level DEFAULT type bound to the NULL/default stream
// (stream 0). Stream choice is the D1 anchor — pick the type whose stream matches
// the consumer's kernels (m11-recon.md R1). Return nullptr on a null backend.
BufferType*    BackendDeviceBufferType(Backend*);
BufferType*    BackendHostBufferType(Backend*);

} // namespace nuka::phi
