#include "oracle/golden_trajectory.hpp"

#include "import/mjcf_importer.hpp"
#include "math/quat.hpp"
#include "math/transform.hpp"
#include "math/vec3.hpp"
#include "phi/device_context.hpp"
#include "runtime/articulation/articulation_state.hpp"
#include "runtime/articulation/featherstone_aba.hpp"
#include "runtime/world_builder.hpp"
#include "scene/cooker.hpp"

#include <gtest/gtest.h>

#include <algorithm>
#include <array>
#include <cstdlib>
#include <cmath>
#include <filesystem>
#include <iostream>
#include <string_view>
#include <vector>

namespace {

std::filesystem::path SourcePath(const char* relative_path) {
    return std::filesystem::path(NUKA_SOURCE_DIR) / relative_path;
}

std::filesystem::path GoldenPath(const char* filename) {
    if (const char* golden_dir = std::getenv("NUKA_GOLDEN_DIR")) {
        if (golden_dir[0] != '\0') {
            return std::filesystem::path(golden_dir) / filename;
        }
    }
    return SourcePath("tests/oracle/golden") / filename;
}

std::vector<float> ComputeCudaAbaQddot(const std::filesystem::path& model_path,
                                       const float* record,
                                       const nuka::tests::oracle::GoldenTrajectory& golden) {
    const auto scene = nuka::import::LoadMjcf(model_path.string());
    const auto blob = nuka::scene::CookScene(scene);
    const auto world = nuka::runtime::BuildWorld(blob);
    auto host_state =
        nuka::runtime::articulation::BuildArticulationHostState(
            world.template_view.articulations,
            world.template_view.body_table);

    // Cook-contract match: the v0.1 random-sample goldens were generated by
    // tools/oracle/generate_mjx_golden.py with _fixed_base_model_xml, i.e. the
    // MJX model has its <freejoint/> stripped so the base is welded to the world
    // (fixed-base, golden nv = 1 dummy root slot + leg DOFs: go2=13, h1=20). The
    // real go2_mjx.xml / h1.xml carry a <freejoint/>, but Nuka's cooker does NOT
    // infer the freejoint -> Free is not in IsSupportedJoint, so it is dropped and
    // never creates an incoming joint; the root then cooks FloatingBase purely via
    // the T8a `root_is_floating = !is_static && BodyMass>0` branch
    // (articulation_cooker.cpp:163-168), because the MJCF importer never sets
    // is_static. So stripping <freejoint/> in the harness would be a no-op here:
    // the honest, EQUIVALENT mirror of the generator's fixed-base contract is to
    // mark the root joint Fixed. The floating and fixed root branches of the
    // cooker differ in exactly one pushed field (joint_types) and produce an
    // identical 13/20-slot DOF layout, so forcing the root to Fixed yields the
    // same cooked topology a true fixed-base cook would (probe: drops worst
    // max_abs from 86.045 -> ~1e-4, identity per-DOF mapping). A genuine
    // floating-base ABA-vs-MJX test lives separately in
    // FloatingBaseRandomSampleGoldensMatchCudaAba.
    for (auto& joint_type : host_state.joint_type) {
        if (joint_type ==
            nuka::runtime::articulation::ArticulationJointType::FloatingBase) {
            joint_type = nuka::runtime::articulation::ArticulationJointType::Fixed;
        }
    }

    if (host_state.q.size() != golden.qpos_count ||
        host_state.qdot.size() != golden.qvel_count ||
        host_state.tau.size() != golden.qvel_count ||
        host_state.qddot.size() != golden.qacc_count) {
        throw std::runtime_error("golden shape does not match cooked articulation");
    }

    const float* qpos = record;
    const float* qvel = qpos + golden.qpos_count;
    const float* tau = qvel + golden.qvel_count;
    std::copy(qpos, qpos + golden.qpos_count, host_state.q.begin());
    std::copy(qvel, qvel + golden.qvel_count, host_state.qdot.begin());
    std::copy(tau, tau + golden.qvel_count, host_state.tau.begin());

    const auto context = nuka::phi::MakeDefaultDeviceContext();
    auto device_state =
        nuka::runtime::articulation::UploadArticulationState(context, host_state);
    nuka::runtime::articulation::FeatherstoneAba::ComputeAccelerations(
        context,
        device_state.View(),
        -9.81f);
    context.stream.Synchronize();
    nuka::runtime::articulation::DownloadArticulationState(device_state, &host_state);
    return host_state.qddot;
}

void ExpectRandomSampleGoldenMatchesCuda(const std::filesystem::path& model_path,
                                         const std::filesystem::path& golden_path) {
    const auto golden = nuka::tests::oracle::LoadGoldenTrajectory(golden_path);
    ASSERT_EQ(golden.kind, nuka::tests::oracle::GoldenKind::RandomQacc);
    ASSERT_EQ(golden.qvel_count, golden.qacc_count);
    constexpr uint32_t kMaxSamplesCheckedInTest = 32u;
    const uint32_t sample_count =
        std::min(golden.sample_count, kMaxSamplesCheckedInTest);
    ASSERT_GT(sample_count, 0u);

    float max_abs = 0.0f;
    for (uint32_t sample = 0u; sample < sample_count; ++sample) {
        const float* record = golden.Record(sample);
        const float* qacc = record + golden.qpos_count +
                            golden.qvel_count + golden.qvel_count;
        const auto qddot = ComputeCudaAbaQddot(model_path, record, golden);
        ASSERT_EQ(qddot.size(), golden.qacc_count);
        for (uint32_t dof = 0u; dof < golden.qacc_count; ++dof) {
            max_abs = std::max(max_abs, std::abs(qddot[dof] - qacc[dof]));
        }
    }

    EXPECT_LE(max_abs, 1.0e-3f)
        << "CUDA Featherstone ABA qddot differs from MJX golden";
}

// ---------------------------------------------------------------------------
// Phase 2: genuine FLOATING-BASE ABA vs MJX comparison.
//
// The floating golden (featherstone_*_floating_random_sample.bin) is generated
// with the <freejoint/> KEPT, so MJX builds the real floating-base model. Record
// layout is RAW MJX: [qpos(nq), qvel(nv), tau(nv), qacc(nv)]. MJX free-joint
// conventions for the base (qvel/qacc DOFs [0:6]):
//   * linear part  [0:3] : WORLD frame
//   * angular part [3:6] : BODY-LOCAL frame
//   * qpos base    [0:7] : pos(3 world), quat(4, w-first)
// Nuka's floating root state is a body-frame SPATIAL 6-vector ordered
// [omega(0:3); v_lin(3:6)] (see featherstone_aba.cu GravityAcceleration -> idx 5
// is world-Z linear; IntegrateFloatingBasePoseKernel comment "body-frame
// [omega(0:3), v_lin(3:6)]"). Nuka cooks ONE scalar slot per link, so the root
// is slot 0 (FloatingBase, scalar qddot[0] is unused / 0) and the base spatial
// acceleration lives in link_acceleration[root]; legs are slots 1..N.
// ---------------------------------------------------------------------------

struct FloatingBaseAbaResult {
    std::vector<float> leg_qddot;     // Nuka per-leg-DOF accel (leg-major).
    std::array<float, 6> base_accel_mjx{};  // base accel in MJX [lin(world); ang(body)] convention.
    std::array<float, 6> base_accel_nuka_spatial{};  // raw Nuka [omega; v_lin] body-frame.
    nuka::math::Quat base_rotation{};
};

// v' = R(q) v, w-first Hamilton; mirrors RotateByQuatForward in featherstone_aba.cu.
nuka::math::Vec3 RotateByQuat(const nuka::math::Quat& q, const nuka::math::Vec3& v) {
    const float n2 = q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z;
    nuka::math::Quat u = q;
    if (n2 > 1.0e-12f) {
        const float inv = 1.0f / std::sqrt(n2);
        u.w *= inv; u.x *= inv; u.y *= inv; u.z *= inv;
    }
    const nuka::math::Vec3 qv{u.x, u.y, u.z};
    const auto cross = [](const nuka::math::Vec3& a, const nuka::math::Vec3& b) {
        return nuka::math::Vec3{a.y * b.z - a.z * b.y,
                                a.z * b.x - a.x * b.z,
                                a.x * b.y - a.y * b.x};
    };
    const nuka::math::Vec3 t{2.0f * cross(qv, v).x, 2.0f * cross(qv, v).y,
                             2.0f * cross(qv, v).z};
    const nuka::math::Vec3 c = cross(qv, t);
    return nuka::math::Vec3{v.x + u.w * t.x + c.x,
                            v.y + u.w * t.y + c.y,
                            v.z + u.w * t.z + c.z};
}

// v_body = R(q)^T v_world.
nuka::math::Vec3 RotateByQuatInverse(const nuka::math::Quat& q, const nuka::math::Vec3& v) {
    nuka::math::Quat inv{q.w, -q.x, -q.y, -q.z};
    return RotateByQuat(inv, v);
}

FloatingBaseAbaResult ComputeCudaAbaFloatingBase(
    const std::filesystem::path& model_path,
    const float* record,
    uint32_t nq, uint32_t nv) {
    const auto scene = nuka::import::LoadMjcf(model_path.string());
    const auto blob = nuka::scene::CookScene(scene);
    const auto world = nuka::runtime::BuildWorld(blob);
    auto host_state =
        nuka::runtime::articulation::BuildArticulationHostState(
            world.template_view.articulations,
            world.template_view.body_table);

    // Cook NATURALLY: do NOT override FloatingBase -> Fixed. Verify the root cooks
    // floating (the whole point of this test).
    if (host_state.ArticulationCount() != 1u) {
        throw std::runtime_error("floating-base oracle expects one articulation");
    }
    const uint32_t root = host_state.articulation_link_offset[0];
    if (host_state.joint_type[root] !=
        nuka::runtime::articulation::ArticulationJointType::FloatingBase) {
        throw std::runtime_error("root did not cook FloatingBase");
    }
    const uint32_t link_count = host_state.articulation_link_count[0];
    const uint32_t leg_dofs = link_count - 1u;  // root slot is unused for DOFs.
    if (nv != leg_dofs + 6u) {
        throw std::runtime_error("floating golden nv != 6 base + Nuka leg DOFs");
    }

    const float* qpos = record;                  // nq
    const float* qvel = qpos + nq;               // nv
    const float* tau  = qvel + nv;               // nv

    // --- INPUT conversion MJX -> Nuka ---------------------------------------
    // Base pose: pos world (qpos[0:3]), quat w-first (qpos[3:7]).
    nuka::math::Transform base_pose;
    base_pose.position = nuka::math::Vec3{qpos[0], qpos[1], qpos[2]};
    nuka::math::Quat base_rot{qpos[3], qpos[4], qpos[5], qpos[6]};
    {
        const float n = std::sqrt(base_rot.w * base_rot.w + base_rot.x * base_rot.x +
                                  base_rot.y * base_rot.y + base_rot.z * base_rot.z);
        const float inv = n > 0.0f ? 1.0f / n : 1.0f;
        base_rot.w *= inv; base_rot.x *= inv; base_rot.y *= inv; base_rot.z *= inv;
    }
    base_pose.rotation = base_rot;
    host_state.base_pose[0] = base_pose;
    // Some FK reads link_pose[root] as the cook seed; keep base_pose authoritative.

    // Base velocity: MJX qvel base = [v_lin world(0:3); omega body(3:6)].
    // Nuka body-frame spatial = [omega(0:3); v_lin body(3:6)].
    const nuka::math::Vec3 v_lin_world{qvel[0], qvel[1], qvel[2]};
    const nuka::math::Vec3 omega_body{qvel[3], qvel[4], qvel[5]};
    const nuka::math::Vec3 v_lin_body = RotateByQuatInverse(base_rot, v_lin_world);
    host_state.link_velocity[root].v[0] = omega_body.x;
    host_state.link_velocity[root].v[1] = omega_body.y;
    host_state.link_velocity[root].v[2] = omega_body.z;
    host_state.link_velocity[root].v[3] = v_lin_body.x;
    host_state.link_velocity[root].v[4] = v_lin_body.y;
    host_state.link_velocity[root].v[5] = v_lin_body.z;

    // Legs: MJX leg DOFs are qvel[6:nv]; Nuka leg slots are root+1 .. root+leg_dofs
    // (identity leg-major mapping, established by the fixed-base oracle).
    for (uint32_t i = 0u; i < leg_dofs; ++i) {
        host_state.q[root + 1u + i]   = qpos[7u + i];
        host_state.qdot[root + 1u + i] = qvel[6u + i];
        host_state.tau[root + 1u + i]  = tau[6u + i];
    }
    // Root scalar slots unused for a floating base.
    host_state.q[root] = 0.0f;
    host_state.qdot[root] = 0.0f;
    host_state.tau[root] = 0.0f;

    constexpr float kGravityZ = -9.81f;
    const auto context = nuka::phi::MakeDefaultDeviceContext();
    auto device_state =
        nuka::runtime::articulation::UploadArticulationState(context, host_state);
    nuka::runtime::articulation::FeatherstoneAba::ComputeAccelerations(
        context, device_state.View(), kGravityZ);
    context.stream.Synchronize();
    nuka::runtime::articulation::DownloadArticulationState(device_state, &host_state);

    FloatingBaseAbaResult result;
    result.base_rotation = base_rot;
    result.leg_qddot.resize(leg_dofs);
    for (uint32_t i = 0u; i < leg_dofs; ++i) {
        result.leg_qddot[i] = host_state.qddot[root + 1u + i];
    }

    // --- OUTPUT conversion Nuka -> MJX --------------------------------------
    // link_acceleration[root] = apparent spatial accel a_0 = (Ia)^-1(-p) in body
    // frame, ordered [omega_dot(0:3); a_lin(3:6)]. Real base generalized accel =
    // a_0 - a_grav, where a_grav (body frame) = [0,0,0; R^T (0,0,-gravity_z)] --
    // exactly what IntegrateFloatingBaseVelocityKernel subtracts.
    float a0[6];
    for (uint32_t i = 0u; i < 6u; ++i) {
        a0[i] = host_state.link_acceleration[root].a[i];
    }
    const nuka::math::Vec3 g_world{0.0f, 0.0f, -kGravityZ};  // GravityAcceleration: out[5]=-g_z
    const nuka::math::Vec3 g_body = RotateByQuatInverse(base_rot, g_world);
    float real[6];
    real[0] = a0[0]; real[1] = a0[1]; real[2] = a0[2];
    real[3] = a0[3] - g_body.x;
    real[4] = a0[4] - g_body.y;
    real[5] = a0[5] - g_body.z;
    for (uint32_t i = 0u; i < 6u; ++i) {
        result.base_accel_nuka_spatial[i] = real[i];
    }
    // Convert Nuka body-frame [omega_dot; a_lin_body] -> MJX [a_lin_world; omega_dot].
    // Nuka's real[3:6] is d/dt(v_lin_body) (the kernel integrates v_lin_body +=
    // real*dt; pose uses x' = R*v_lin_body). MJX qacc[0:3] is d/dt(v_lin_world) =
    // d/dt(R*v_lin_body) = R*(d/dt(v_lin_body) + omega_body x v_lin_body). So the
    // spatial->classical linear-accel term is omega_body x v_lin_body, added in the
    // body frame BEFORE rotating to world (vanishes at zero base velocity).
    const nuka::math::Vec3 omega_dot{real[0], real[1], real[2]};
    const nuka::math::Vec3 a_lin_body_spatial{real[3], real[4], real[5]};
    const nuka::math::Vec3 omega_cross_v{
        omega_body.y * v_lin_body.z - omega_body.z * v_lin_body.y,
        omega_body.z * v_lin_body.x - omega_body.x * v_lin_body.z,
        omega_body.x * v_lin_body.y - omega_body.y * v_lin_body.x};
    const nuka::math::Vec3 a_lin_body{
        a_lin_body_spatial.x + omega_cross_v.x,
        a_lin_body_spatial.y + omega_cross_v.y,
        a_lin_body_spatial.z + omega_cross_v.z};
    const nuka::math::Vec3 a_lin_world = RotateByQuat(base_rot, a_lin_body);
    result.base_accel_mjx = {a_lin_world.x, a_lin_world.y, a_lin_world.z,
                             omega_dot.x, omega_dot.y, omega_dot.z};
    return result;
}

void RunFloatingBaseOracle(const std::filesystem::path& model_path,
                           const std::filesystem::path& golden_path,
                           const char* label) {
    const auto golden = nuka::tests::oracle::LoadGoldenTrajectory(golden_path);
    ASSERT_EQ(golden.kind, nuka::tests::oracle::GoldenKind::RandomQacc);
    const uint32_t nq = golden.qpos_count;
    const uint32_t nv = golden.qvel_count;
    ASSERT_EQ(golden.qacc_count, nv);
    constexpr uint32_t kMaxSamples = 32u;
    const uint32_t sample_count = std::min(golden.sample_count, kMaxSamples);
    ASSERT_GT(sample_count, 0u);

    float leg_max_abs = 0.0f;
    float base_lin_max_abs = 0.0f;
    float base_ang_max_abs = 0.0f;
    for (uint32_t sample = 0u; sample < sample_count; ++sample) {
        const float* record = golden.Record(sample);
        const float* qacc = record + static_cast<size_t>(nq) + nv + nv;
        const auto out = ComputeCudaAbaFloatingBase(model_path, record, nq, nv);
        // Legs: MJX qacc[6:nv] vs Nuka leg qddot (identity leg-major).
        for (uint32_t i = 0u; i < out.leg_qddot.size(); ++i) {
            leg_max_abs = std::max(leg_max_abs,
                                   std::abs(out.leg_qddot[i] - qacc[6u + i]));
        }
        // Base: MJX qacc[0:6] = [a_lin world(0:3); omega_dot body(3:6)].
        for (uint32_t i = 0u; i < 3u; ++i) {
            base_lin_max_abs = std::max(base_lin_max_abs,
                                        std::abs(out.base_accel_mjx[i] - qacc[i]));
            base_ang_max_abs = std::max(base_ang_max_abs,
                                        std::abs(out.base_accel_mjx[3u + i] - qacc[3u + i]));
        }
    }

    std::cout << "[FloatingBase " << label << "] over " << sample_count
              << " samples: leg_max_abs=" << leg_max_abs
              << "  base_lin_max_abs=" << base_lin_max_abs
              << "  base_ang_max_abs=" << base_ang_max_abs << std::endl;

    // Legs are frame-invariant joint-angle accelerations: this is the genuine,
    // well-defined floating-base ABA-vs-MJX leg-coupling test.
    EXPECT_LE(leg_max_abs, 1.0e-3f)
        << "[" << label << "] floating-base leg qddot differs from MJX qacc";
    // Base 6 DOFs: spatial-vs-classical accel + free-joint frame convention.
    // Reported (not silently hidden); see characterization comment in the TEST.
    EXPECT_LE(base_lin_max_abs, 1.0e-3f)
        << "[" << label << "] floating-base linear accel differs from MJX";
    EXPECT_LE(base_ang_max_abs, 1.0e-3f)
        << "[" << label << "] floating-base angular accel differs from MJX";
}

} // namespace

TEST(FeatherstoneOracle, GoldenFilesAreOwnerProvided) {
    const auto go2 = GoldenPath("featherstone_go2_random_sample.bin");
    const auto h1 = GoldenPath("featherstone_h1_random_sample.bin");
    const auto stand = GoldenPath("go2_stand_5s.bin");
    if (!std::filesystem::exists(go2) ||
        !std::filesystem::exists(h1) ||
        !std::filesystem::exists(stand)) {
        GTEST_SKIP() << "v0.1 golden files are owner-protected and not present";
    }

    for (const auto& path : {go2, h1, stand}) {
        const auto golden = nuka::tests::oracle::LoadGoldenTrajectory(path);
        EXPECT_GT(golden.sample_count, 0u) << path;
        EXPECT_GT(golden.qpos_count, 0u) << path;
        if (golden.kind == nuka::tests::oracle::GoldenKind::RandomQacc) {
            EXPECT_GT(golden.qvel_count, 0u) << path;
            EXPECT_GT(golden.qacc_count, 0u) << path;
        }
        EXPECT_EQ(golden.payload.size(),
                  static_cast<size_t>(golden.sample_count) * golden.RecordFloatCount())
            << path;
    }
}

TEST(FeatherstoneOracle, RandomSampleGoldenShapeMatchesV1Contract) {
    const auto go2 = GoldenPath("featherstone_go2_random_sample.bin");
    const auto h1 = GoldenPath("featherstone_h1_random_sample.bin");
    if (!std::filesystem::exists(go2) || !std::filesystem::exists(h1)) {
        GTEST_SKIP() << "v0.1 random-sample golden files are owner-protected and not present";
    }

    for (const auto& path : {go2, h1}) {
        const auto golden = nuka::tests::oracle::LoadGoldenTrajectory(path);
        EXPECT_EQ(golden.kind, nuka::tests::oracle::GoldenKind::RandomQacc) << path;
        EXPECT_EQ(golden.sample_count, 1000u) << path;
        EXPECT_EQ(golden.qvel_count, golden.qacc_count) << path;
    }
}

TEST(FeatherstoneOracle, RandomSampleGoldensMatchCudaAba) {
    const auto go2_model =
        SourcePath(".nuka-assets/mujoco_menagerie/unitree_go2/go2_mjx.xml");
    const auto h1_model =
        SourcePath(".nuka-assets/mujoco_menagerie/unitree_h1/h1.xml");
    const auto go2_golden =
        GoldenPath("featherstone_go2_random_sample.bin");
    const auto h1_golden =
        GoldenPath("featherstone_h1_random_sample.bin");

    if (!std::filesystem::exists(go2_model) || !std::filesystem::exists(h1_model)) {
        GTEST_SKIP() << "MuJoCo Menagerie Go2/H1 assets are not available";
    }
    if (!std::filesystem::exists(go2_golden) || !std::filesystem::exists(h1_golden)) {
        GTEST_SKIP() << "v0.1 random-sample golden files are owner-protected and not present";
    }

    ExpectRandomSampleGoldenMatchesCuda(go2_model, go2_golden);
    ExpectRandomSampleGoldenMatchesCuda(h1_model, h1_golden);
}

// Phase 2: genuine floating-base ABA vs MJX. ADDITIVE -- the existing fixed-base
// goldens and tests above are untouched. Uses a floating golden generated with
// the <freejoint/> KEPT but <actuator>+<keyframe> STRIPPED
// (tools/oracle/generate_mjx_golden.py --mode floating-random-qacc), so MJX
// builds the real floating-base model (go2 nv=18/nq=19) while its qacc carries
// NO servo-bias force.
//
// The floating-base ABA is CLEAN (a controlled MJX-vs-Nuka isolation proved it:
// free-fall to 1e-6, leg-torque to 3.4e-5, random orient+vel to ~6e-5). This test
// reaches GREEN once two TEST-INFRA pieces are in place, both now done:
//   (1) GENERATOR strips <actuator>+<keyframe> from the floating model. go2's 12
//       position servos otherwise inject qfrc_actuator (biasprm position/velocity
//       feedback) into MJX qacc even at ctrl=0 -- a force Nuka's bare-tau ABA does
//       not and should not model (this was the dominant red term). Stripping
//       mirrors _fixed_base_model_xml; the freejoint is KEPT so the base floats.
//   (2) HARNESS adds the omega x v_lin spatial->classical linear-accel term in
//       ComputeCudaAbaFloatingBase's Nuka[a_lin body]->MJX[a_lin world]
//       conversion. Nuka's real[3:6] is d/dt(v_lin_body); MJX qacc[0:3] is
//       d/dt(v_lin_world) = R*(d/dt(v_lin_body) + omega_body x v_lin_body). The
//       term vanishes at zero base velocity (which is why it was the only residual
//       after (1)) and is required to match at nonzero base velocity.
//
// SCOPE: this validates the ABA's force->accel response only, via leg-tau
// injection. The standing golden additionally routes foot CONTACT forces into the
// base through the contact/constraint solver -- not leg tau -- which this test
// does not exercise; that path's correctness is a separate question.
TEST(FeatherstoneOracle, FloatingBaseRandomSampleGoldensMatchCudaAba) {
    const auto go2_model =
        SourcePath(".nuka-assets/mujoco_menagerie/unitree_go2/go2_mjx.xml");
    const auto go2_golden =
        GoldenPath("featherstone_go2_floating_random_sample.bin");

    if (!std::filesystem::exists(go2_model)) {
        GTEST_SKIP() << "MuJoCo Menagerie Go2 assets are not available";
    }
    if (!std::filesystem::exists(go2_golden)) {
        GTEST_SKIP() << "floating-base golden not present (run generator --mode "
                        "floating-random-qacc)";
    }

    RunFloatingBaseOracle(go2_model, go2_golden, "go2");
}
