#pragma once
// ---------------------------------------------------------------------------
// nuka::constraint -- collidable LEAF kind enums (v0.8 C2a)
// ---------------------------------------------------------------------------
// Hand-authored, dependency-free leaf header. These three small enums name the
// runtime "providers" each collidable type is wired to at WORLD BUILD (C2b/C2c):
//   - AccelStructureKind   : which broadphase accel structure indexes this type
//   - ShapeProxyKind       : how the type's geometry is presented to narrowphase
//   - ReactionProviderKind : which reaction (inverse-mass / Jacobian) model the
//                            solver uses for this type's side of a contact row
//
// WHY A SEPARATE LEAF HEADER. The collidable-type REGISTRY (enum CollidableType
// + the static metadata table) is GENERATED by the codegen system into
//   src/codegen/generated/collidable_registry.hpp
// That generated header must reference these kind enums in its constexpr table.
// Keeping the kinds in this no-deps leaf breaks the include cycle:
//   collidable_kinds.hpp (leaf)  ->  generated collidable_registry.hpp
//                                ->  collidable.hpp (the runtime ref + seam)
// The generated header #includes THIS file; nothing here includes the generated
// header. So the DAG is acyclic.
//
// THESE ENUMS ARE STATIC METADATA SELECTORS, not function pointers. The actual
// device function pointers (e.g. the per-type compute_aabbs AABB provider, the
// §0.4 seam) are resolved at world build by C2b/C2c -- see collidable.hpp.
// ---------------------------------------------------------------------------

#include <cstdint>

namespace nuka::constraint {

// Which broadphase acceleration structure indexes a collidable of this type.
// LbvhRigid: the rigid LBVH (broadphase_lbvh). UniformGridParticle: the particle
// spatial-hash grid (particle_uniform_grid). None: never broadphased (e.g. the
// static world is queried directly, not indexed into a rebuilt-per-step tree).
enum class AccelStructureKind : uint8_t {
    LbvhRigid           = 0u,
    UniformGridParticle = 1u,
    None                = 2u,
};

// How a collidable's geometry is presented to narrowphase. ShapeBacked: a
// cooked Shape (SDF / mesh / primitive) carried by the body. PointSphere: a
// single point + radius (particles). None: no narrowphase geometry.
enum class ShapeProxyKind : uint8_t {
    ShapeBacked = 0u,
    PointSphere = 1u,
    None        = 2u,
};

// Which reaction model the solver uses for this type's side of a contact row.
// RigidInvMass: a maximal rigid body's 6x6 inverse mass. ArticulationChainJ:
// the Featherstone chain Jacobian of an articulation link. ParticleInvMass: a
// particle pseudo-body's scalar inverse mass. StaticNull: an immovable world
// collider (infinite mass -> zero reaction, no DOFs).
enum class ReactionProviderKind : uint8_t {
    RigidInvMass      = 0u,
    ArticulationChainJ = 1u,
    ParticleInvMass   = 2u,
    StaticNull        = 3u,
};

} // namespace nuka::constraint
