// ---------------------------------------------------------------------------
// PHI v2 (M1) smoke gate — the plan-mandated scenario test.
//
// Exercises the full ggml-style multi-backend layer end-to-end on real CUDA:
//   1. Registry: enumerate -> find CUDA entry -> device 0 -> init backend.
//   2. Buffer:   alloc device buffer -> upload -> download -> byte roundtrip.
//   3. dispatch: run a test vector-add op via BackendI::dispatch -> sync ->
//                download -> check vs CPU reference.
//   4. plan:     plan_create the same OpCall list -> plan_execute -> identical
//                result; replay a SECOND time -> bytes IDENTICAL (D1).
//   5. event:    event_new / record / wait / free along the way (smoke only).
//
// ModelView / DataView are only FORWARD-DECLARED in phi (generated by codegen
// in M3). The test provides minimal empty local DEFINITIONS so it can
// instantiate them and pass references through dispatch / plan_create. Ops never
// dereference them in M1, so empty definitions are sufficient and correct. This
// is the cleanest approach that compiles: phi headers only forward-declare, the
// test owns the definition, nothing else in the layer needs the layout.
// ---------------------------------------------------------------------------

#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <vector>

#include "phi/backend.hpp"
#include "phi/buffer.hpp"

#include "phi2_smoke_ops.hpp"

// Minimal local definitions for the two forward-declared view types. Empty is
// sufficient: nothing in M1 dereferences them.
namespace nuka::phi {
struct ModelView {};
struct DataView {};
} // namespace nuka::phi

namespace {

using namespace nuka::phi;

// Find the CUDA registry entry by name; returns nullptr if absent.
RegistryEntry* FindCudaEntry() {
    const size_t n = BackendCount();
    for (size_t i = 0; i < n; ++i) {
        RegistryEntry* e = GetBackend(i);
        if (e != nullptr && std::strcmp(RegistryEntryName(e), "cuda") == 0) {
            return e;
        }
    }
    return nullptr;
}

} // namespace

class Phi2SmokeTest : public ::testing::Test {
protected:
    void SetUp() override {
        nuka::phi_smoke::RegisterVecAddOp();  // plant the test op once per test
    }
};

TEST_F(Phi2SmokeTest, RegistryEnumeratesCudaAndInitsBackend) {
    ASSERT_GT(BackendCount(), 0u) << "no backends registered";
    RegistryEntry* entry = FindCudaEntry();
    ASSERT_NE(entry, nullptr) << "CUDA registry entry not found";
    ASSERT_GT(RegistryEntryDeviceCount(entry), 0u) << "no CUDA devices";

    Device* dev = RegistryEntryGetDevice(entry, 0);
    ASSERT_NE(dev, nullptr);

    Backend* backend = DeviceInitBackend(dev, /*params_json=*/nullptr);
    ASSERT_NE(backend, nullptr);
    EXPECT_STREQ(BackendName(backend), "cuda");
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, DeviceBufferByteRoundtrip) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    BufferType* bt = DeviceBufferType(dev);
    ASSERT_NE(bt, nullptr);
    EXPECT_EQ(BufferTypeAlignment(bt), 256u);
    EXPECT_FALSE(BufferTypeIsHost(bt));

    const size_t n_bytes = 1024;
    Buffer* buf = BufferAlloc(bt, n_bytes);
    ASSERT_NE(buf, nullptr);
    ASSERT_NE(BufferBase(buf), nullptr);

    std::vector<std::uint8_t> src(n_bytes);
    for (size_t i = 0; i < n_bytes; ++i) {
        src[i] = static_cast<std::uint8_t>((i * 31 + 7) & 0xFF);
    }
    BufferUpload(buf, src.data(), /*off=*/0, n_bytes);

    std::vector<std::uint8_t> dst(n_bytes, 0);
    BufferDownload(buf, dst.data(), /*off=*/0, n_bytes);

    EXPECT_EQ(src, dst);  // byte roundtrip

    BufferFree(buf);
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, DispatchAndPlanVectorAddDeterministic) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    EXPECT_TRUE(DeviceSupportsOp(dev, NkOp::ApplyDrives))
        << "test op should be registered into the ApplyDrives slot";

    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    BufferType* bt = DeviceBufferType(dev);
    ASSERT_NE(bt, nullptr);

    const int n = 4096;
    const size_t n_bytes = static_cast<size_t>(n) * sizeof(float);

    std::vector<float> ha(n), hb(n), ref(n);
    for (int i = 0; i < n; ++i) {
        ha[i] = static_cast<float>(i) * 0.5f;
        hb[i] = static_cast<float>(n - i) * 0.25f;
        ref[i] = ha[i] + hb[i];
    }

    Buffer* ba = BufferAlloc(bt, n_bytes);
    Buffer* bb = BufferAlloc(bt, n_bytes);
    Buffer* bc = BufferAlloc(bt, n_bytes);
    ASSERT_NE(ba, nullptr);
    ASSERT_NE(bb, nullptr);
    ASSERT_NE(bc, nullptr);

    BufferUpload(ba, ha.data(), 0, n_bytes);
    BufferUpload(bb, hb.data(), 0, n_bytes);

    nuka::phi_smoke::VecAddParams params{};
    params.a = static_cast<const float*>(BufferBase(ba));
    params.b = static_cast<const float*>(BufferBase(bb));
    params.c = static_cast<float*>(BufferBase(bc));
    params.n = n;

    OpCall call{NkOp::ApplyDrives, &params};
    ModelView model{};
    DataView data{};

    // --- event smoke (record before, wait after; no assertion beyond OK) ---
    Event* ev = BackendEventNew(backend);
    ASSERT_NE(ev, nullptr);
    BackendEventRecord(backend, ev);

    // --- dispatch path ---------------------------------------------------
    BufferMemset(bc, 0, 0, n_bytes);  // clear output
    ASSERT_EQ(BackendDispatch(backend, model, data, call), Status::Ok);
    BackendEventWait(backend, ev);    // main stream waits on the recorded event
    BackendSynchronize(backend);

    std::vector<float> dispatch_out(n, -1.0f);
    BufferDownload(bc, dispatch_out.data(), 0, n_bytes);
    for (int i = 0; i < n; ++i) {
        ASSERT_FLOAT_EQ(dispatch_out[i], ref[i]) << "dispatch mismatch at " << i;
    }

    BackendEventFree(backend, ev);

    // --- plan path (CUDA-graph capture + replay) -------------------------
    BufferMemset(bc, 0, 0, n_bytes);
    BackendSynchronize(backend);

    Plan* plan = BackendPlanCreate(backend, model, data, &call, /*n_calls=*/1);
    ASSERT_NE(plan, nullptr) << "plan_create (stream capture) failed";

    ASSERT_EQ(BackendPlanExecute(backend, plan), Status::Ok);
    BackendSynchronize(backend);

    std::vector<float> plan_out1(n, -1.0f);
    BufferDownload(bc, plan_out1.data(), 0, n_bytes);
    for (int i = 0; i < n; ++i) {
        ASSERT_FLOAT_EQ(plan_out1[i], ref[i]) << "plan replay #1 mismatch at " << i;
    }
    // plan result must equal the dispatch result.
    EXPECT_EQ(plan_out1, dispatch_out);

    // --- second replay: re-upload identical inputs, re-clear output, replay
    // again -> downloaded bytes must be BIT-IDENTICAL (D1 determinism). ------
    BufferUpload(ba, ha.data(), 0, n_bytes);
    BufferUpload(bb, hb.data(), 0, n_bytes);
    BufferMemset(bc, 0, 0, n_bytes);
    BackendSynchronize(backend);

    ASSERT_EQ(BackendPlanExecute(backend, plan), Status::Ok);
    BackendSynchronize(backend);

    std::vector<float> plan_out2(n, -2.0f);
    BufferDownload(bc, plan_out2.data(), 0, n_bytes);

    ASSERT_EQ(plan_out1.size(), plan_out2.size());
    EXPECT_EQ(std::memcmp(plan_out1.data(), plan_out2.data(),
                          plan_out1.size() * sizeof(float)),
              0)
        << "two plan replays are not byte-identical (D1 violation)";

    BackendPlanFree(backend, plan);
    BufferFree(ba);
    BufferFree(bb);
    BufferFree(bc);
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, UnregisteredOpReturnsUnsupported) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    // AbaForward has no implementation in M1 -> Unsupported.
    EXPECT_FALSE(DeviceSupportsOp(dev, NkOp::AbaForward));
    OpCall call{NkOp::AbaForward, nullptr};
    ModelView model{};
    DataView data{};
    EXPECT_EQ(BackendDispatch(backend, model, data, call), Status::Unsupported);

    BackendFree(backend);
}
