// ---------------------------------------------------------------------------
// PHI v2 (M1) smoke gate — the plan-mandated scenario test.
//
// Exercises the full ggml-style multi-backend layer end-to-end on real CUDA:
//   1. Registry: enumerate -> find CUDA entry -> device 0 -> init backend.
//   2. Buffer:   alloc device buffer -> upload -> download -> byte roundtrip.
//   3. dispatch: run a test vector-add op via BackendI::dispatch -> sync ->
//                download -> check vs CPU reference.
//   4. plan:     plan_create the same OpCall list -> plan_execute -> identical
//                result; replay a SECOND time -> bytes IDENTICAL (D1).
//   5. event:    event_new / record / wait / free along the way (smoke only).
//
// ModelView / DataView are only FORWARD-DECLARED in phi (generated by codegen
// in M3). The test provides minimal empty local DEFINITIONS so it can
// instantiate them and pass references through dispatch / plan_create. Ops never
// dereference them in M1, so empty definitions are sufficient and correct. This
// is the cleanest approach that compiles: phi headers only forward-declare, the
// test owns the definition, nothing else in the layer needs the layout.
// ---------------------------------------------------------------------------

#include <gtest/gtest.h>

#include <cstdint>
#include <cstring>
#include <vector>

#include "phi/backend.hpp"
#include "phi/buffer.hpp"

// M3a: the REAL ModelView / DataView definitions are now GENERATED. The smoke
// test includes the generated header instead of defining empty local stubs
// (ODR hygiene — there is now exactly ONE definition of each view type, used by
// both the M1 op-dispatch tests and the M3a NkWorldSkeleton test below).
#include "nk/model/generated/views.hpp"

#include "phi2_smoke_ops.hpp"

// --- M3a nk core (the NkWorldSkeleton acceptance case) -----------------------
#include "nk/model/model.hpp"
#include "nk/pipeline/world.hpp"
#include "nk/model/generated/field_ids.hpp"
#include "scene/cook/cook_to_model.hpp"
#include "scene/scene_ir.hpp"

namespace {

using namespace nuka::phi;

// Find the CUDA registry entry by name; returns nullptr if absent.
RegistryEntry* FindCudaEntry() {
    const size_t n = BackendCount();
    for (size_t i = 0; i < n; ++i) {
        RegistryEntry* e = GetBackend(i);
        if (e != nullptr && std::strcmp(RegistryEntryName(e), "cuda") == 0) {
            return e;
        }
    }
    return nullptr;
}

} // namespace

class Phi2SmokeTest : public ::testing::Test {
protected:
    void SetUp() override {
        // M3b: force the built-in registration (CUDA entry + the REAL
        // articulation ops) FIRST, then plant the test op over the ApplyDrives
        // slot — SetCudaOp is last-wins, so the override is deterministic
        // regardless of which test runs first.
        (void)InitBestDevice();
        nuka::phi_smoke::RegisterVecAddOp();  // plant the test op once per test
    }
};

TEST_F(Phi2SmokeTest, RegistryEnumeratesCudaAndInitsBackend) {
    ASSERT_GT(BackendCount(), 0u) << "no backends registered";
    RegistryEntry* entry = FindCudaEntry();
    ASSERT_NE(entry, nullptr) << "CUDA registry entry not found";
    ASSERT_GT(RegistryEntryDeviceCount(entry), 0u) << "no CUDA devices";

    Device* dev = RegistryEntryGetDevice(entry, 0);
    ASSERT_NE(dev, nullptr);

    Backend* backend = DeviceInitBackend(dev, /*params_json=*/nullptr);
    ASSERT_NE(backend, nullptr);
    EXPECT_STREQ(BackendName(backend), "cuda");
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, DeviceBufferByteRoundtrip) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    BufferType* bt = DeviceBufferType(dev);
    ASSERT_NE(bt, nullptr);
    EXPECT_EQ(BufferTypeAlignment(bt), 256u);
    EXPECT_FALSE(BufferTypeIsHost(bt));

    const size_t n_bytes = 1024;
    Buffer* buf = BufferAlloc(bt, n_bytes);
    ASSERT_NE(buf, nullptr);
    ASSERT_NE(BufferBase(buf), nullptr);

    std::vector<std::uint8_t> src(n_bytes);
    for (size_t i = 0; i < n_bytes; ++i) {
        src[i] = static_cast<std::uint8_t>((i * 31 + 7) & 0xFF);
    }
    BufferUpload(buf, src.data(), /*off=*/0, n_bytes);

    std::vector<std::uint8_t> dst(n_bytes, 0);
    BufferDownload(buf, dst.data(), /*off=*/0, n_bytes);

    EXPECT_EQ(src, dst);  // byte roundtrip

    BufferFree(buf);
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, DispatchAndPlanVectorAddDeterministic) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    EXPECT_TRUE(DeviceSupportsOp(dev, NkOp::ApplyDrives))
        << "test op should be registered into the ApplyDrives slot";

    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    BufferType* bt = DeviceBufferType(dev);
    ASSERT_NE(bt, nullptr);

    const int n = 4096;
    const size_t n_bytes = static_cast<size_t>(n) * sizeof(float);

    std::vector<float> ha(n), hb(n), ref(n);
    for (int i = 0; i < n; ++i) {
        ha[i] = static_cast<float>(i) * 0.5f;
        hb[i] = static_cast<float>(n - i) * 0.25f;
        ref[i] = ha[i] + hb[i];
    }

    Buffer* ba = BufferAlloc(bt, n_bytes);
    Buffer* bb = BufferAlloc(bt, n_bytes);
    Buffer* bc = BufferAlloc(bt, n_bytes);
    ASSERT_NE(ba, nullptr);
    ASSERT_NE(bb, nullptr);
    ASSERT_NE(bc, nullptr);

    BufferUpload(ba, ha.data(), 0, n_bytes);
    BufferUpload(bb, hb.data(), 0, n_bytes);

    nuka::phi_smoke::VecAddParams params{};
    params.a = static_cast<const float*>(BufferBase(ba));
    params.b = static_cast<const float*>(BufferBase(bb));
    params.c = static_cast<float*>(BufferBase(bc));
    params.n = n;

    OpCall call{NkOp::ApplyDrives, &params};
    ModelView model{};
    DataView data{};

    // --- event smoke (record before, wait after; no assertion beyond OK) ---
    Event* ev = BackendEventNew(backend);
    ASSERT_NE(ev, nullptr);
    BackendEventRecord(backend, ev);

    // --- dispatch path ---------------------------------------------------
    BufferMemset(bc, 0, 0, n_bytes);  // clear output
    ASSERT_EQ(BackendDispatch(backend, model, data, call), Status::Ok);
    BackendEventWait(backend, ev);    // main stream waits on the recorded event
    BackendSynchronize(backend);

    std::vector<float> dispatch_out(n, -1.0f);
    BufferDownload(bc, dispatch_out.data(), 0, n_bytes);
    for (int i = 0; i < n; ++i) {
        ASSERT_FLOAT_EQ(dispatch_out[i], ref[i]) << "dispatch mismatch at " << i;
    }

    BackendEventFree(backend, ev);

    // --- plan path (CUDA-graph capture + replay) -------------------------
    BufferMemset(bc, 0, 0, n_bytes);
    BackendSynchronize(backend);

    Plan* plan = BackendPlanCreate(backend, model, data, &call, /*n_calls=*/1);
    ASSERT_NE(plan, nullptr) << "plan_create (stream capture) failed";

    ASSERT_EQ(BackendPlanExecute(backend, plan), Status::Ok);
    BackendSynchronize(backend);

    std::vector<float> plan_out1(n, -1.0f);
    BufferDownload(bc, plan_out1.data(), 0, n_bytes);
    for (int i = 0; i < n; ++i) {
        ASSERT_FLOAT_EQ(plan_out1[i], ref[i]) << "plan replay #1 mismatch at " << i;
    }
    // plan result must equal the dispatch result.
    EXPECT_EQ(plan_out1, dispatch_out);

    // --- second replay: re-upload identical inputs, re-clear output, replay
    // again -> downloaded bytes must be BIT-IDENTICAL (D1 determinism). ------
    BufferUpload(ba, ha.data(), 0, n_bytes);
    BufferUpload(bb, hb.data(), 0, n_bytes);
    BufferMemset(bc, 0, 0, n_bytes);
    BackendSynchronize(backend);

    ASSERT_EQ(BackendPlanExecute(backend, plan), Status::Ok);
    BackendSynchronize(backend);

    std::vector<float> plan_out2(n, -2.0f);
    BufferDownload(bc, plan_out2.data(), 0, n_bytes);

    ASSERT_EQ(plan_out1.size(), plan_out2.size());
    EXPECT_EQ(std::memcmp(plan_out1.data(), plan_out2.data(),
                          plan_out1.size() * sizeof(float)),
              0)
        << "two plan replays are not byte-identical (D1 violation)";

    BackendPlanFree(backend, plan);
    BufferFree(ba);
    BufferFree(bb);
    BufferFree(bc);
    BackendFree(backend);
}

TEST_F(Phi2SmokeTest, UnregisteredOpReturnsUnsupported) {
    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    // The probe op must be one with no implementation yet. M3b registered
    // AbaForward; M5 registered LbvhBuild; M6 registered XpbdProject (the whole
    // particle spine) — so the former XpbdProject probe is now supported. The
    // next still-unimplemented milestone op is the M9 domain-randomization op
    // RandomizeMaterialBuckets.
    EXPECT_TRUE(DeviceSupportsOp(dev, NkOp::AbaForward))
        << "M3b: the real AbaForward op should be registered";
    EXPECT_TRUE(DeviceSupportsOp(dev, NkOp::LbvhBuild))
        << "M5: the real LbvhBuild broadphase op should be registered";
    EXPECT_TRUE(DeviceSupportsOp(dev, NkOp::XpbdProject))
        << "M6: the real XpbdProject particle op should be registered";
    EXPECT_FALSE(DeviceSupportsOp(dev, NkOp::RandomizeMaterialBuckets));
    OpCall call{NkOp::RandomizeMaterialBuckets, nullptr};
    ModelView model{};
    DataView data{};
    EXPECT_EQ(BackendDispatch(backend, model, data, call), Status::Unsupported);

    BackendFree(backend);
}

// ---------------------------------------------------------------------------
// M3a acceptance evidence: build a tiny programmatic SceneIR (one body + one
// sphere shape), CookToModel(env_count=2), construct an nk::World, and assert:
//   * arena segment layout is DETERMINISTIC (two CookToModel+layout passes
//     produce identical segment tables),
//   * FieldPtr is non-null for q / qdot (data-owned) once the World is built,
//   * Step() returns the EXPECTED per-op Unsupported statuses (no op is
//     registered for the real pipeline in M3a),
//   * Reset() does not crash.
// ---------------------------------------------------------------------------
TEST_F(Phi2SmokeTest, NkWorldSkeleton) {
    using namespace nuka;

    // NOTE: the smoke fixture planted the test VecAdd op into the ApplyDrives
    // slot, but a one-body (no-articulation) scene's pipeline never EMITS
    // ApplyDrives (it is articulation-only), so the override cannot collide
    // with the real M3b pipeline dispatched below.

    Device* dev = InitBestDevice();
    ASSERT_NE(dev, nullptr);
    Backend* backend = DeviceInitBackend(dev, nullptr);
    ASSERT_NE(backend, nullptr);

    // --- tiny scene: one dynamic body carrying one sphere collision shape ---
    auto build_scene = []() {
        scene::SceneIR s;
        scene::RigidBodyRecord body;
        body.name = "ball";
        body.mass = 1.0f;
        const scene::BodyId bid = s.AddRigidBody(body);
        scene::CollisionShapeRecord shape;
        shape.body_id = bid;
        shape.type = scene::ShapeType::Sphere;
        shape.radius = 0.1f;
        s.AddCollisionShape(shape);
        return s;
    };

    // --- determinism: two independent cooks => identical arena segment table ---
    const scene::SceneIR scene_a = build_scene();
    const scene::SceneIR scene_b = build_scene();
    auto cooked_a = scene::cook::CookToModel(scene_a, /*env_count=*/2);
    auto cooked_b = scene::cook::CookToModel(scene_b, /*env_count=*/2);

    uint64_t bytes_a[3] = {0, 0, 0};
    uint64_t bytes_b[3] = {0, 0, 0};
    const auto segs_a = nk::Arena::ComputeSegments(cooked_a.model.capacities, bytes_a);
    const auto segs_b = nk::Arena::ComputeSegments(cooked_b.model.capacities, bytes_b);
    ASSERT_EQ(segs_a.size(), segs_b.size());
    for (size_t i = 0; i < segs_a.size(); ++i) {
        EXPECT_EQ(segs_a[i].field, segs_b[i].field) << "segment field differs at " << i;
        EXPECT_EQ(segs_a[i].arena, segs_b[i].arena) << "segment arena differs at " << i;
        EXPECT_EQ(segs_a[i].offset, segs_b[i].offset) << "segment offset differs at " << i;
        EXPECT_EQ(segs_a[i].bytes, segs_b[i].bytes) << "segment bytes differs at " << i;
    }
    EXPECT_EQ(bytes_a[0], bytes_b[0]);
    EXPECT_EQ(bytes_a[1], bytes_b[1]);
    EXPECT_EQ(bytes_a[2], bytes_b[2]);

    // SceneMap: the body + shape entities bound to cooked rows.
    EXPECT_GT(cooked_a.scene_map.Size(), 0u);

    // --- construct the World (uploads Model, allocates Data, builds Pipeline) ---
    nk::World world(std::move(cooked_a.model), /*env_count=*/2, dev, backend);
    ASSERT_TRUE(world.Ready());
    EXPECT_EQ(world.EnvCount(), 2u);

    // FieldPtr non-null for the data-owned q / qdot.
    EXPECT_NE(world.FieldPtr(nk::FieldId::Q), nullptr);
    EXPECT_NE(world.FieldPtr(nk::FieldId::Qdot), nullptr);
    // body_pose is data-owned; the body the scene authored exists.
    EXPECT_NE(world.FieldPtr(nk::FieldId::BodyPose), nullptr);

    // Step(): the pipeline has a non-empty op list (the body has a collidable).
    // M3b: the capability query (§3.1 supports_op) drops the not-yet-implemented
    // M5/M6 ops at Build, and every EMITTED op is a registered M3b op that
    // dispatches Ok (no-op gracefully on this articulation-free scene).
    const nk::StepResult res = world.Step();
    EXPECT_GT(res.OpCount(), 0u) << "the one-body scene should emit a non-empty pipeline";
    EXPECT_TRUE(res.AllOk())
        << "M3b: every emitted op is registered and must dispatch Ok";

    // Reset is now the DEVICE-side bulk RestoreState op -> Ok.
    EXPECT_EQ(world.Reset(), Status::Ok);

    // A second Step after Reset still works (no state corruption).
    const nk::StepResult res2 = world.Step();
    EXPECT_EQ(res2.OpCount(), res.OpCount());

    BackendFree(backend);
}
