function(nuka_verify_viewer_font path sha256 option)
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "${option} does not exist: ${path}")
    endif()
    file(SHA256 "${path}" actual)
    if(NOT actual STREQUAL sha256)
        message(FATAL_ERROR "${option} checksum mismatch: use the pinned official font")
    endif()
endfunction()

function(nuka_download_viewer_font url path sha256 option)
    if(NOT EXISTS "${path}")
        get_filename_component(directory "${path}" DIRECTORY)
        file(MAKE_DIRECTORY "${directory}")
        file(DOWNLOAD "${url}" "${path}.download" TLS_VERIFY ON STATUS result)
        list(GET result 0 code)
        if(NOT code EQUAL 0)
            file(REMOVE "${path}.download")
            message(FATAL_ERROR "Font download failed. Set ${option} to an offline copy: ${result}")
        endif()
        file(SHA256 "${path}.download" actual)
        if(NOT actual STREQUAL sha256)
            file(REMOVE "${path}.download")
            message(FATAL_ERROR "Font download checksum mismatch. Set ${option} to the pinned official offline copy")
        endif()
        file(RENAME "${path}.download" "${path}")
    endif()
    nuka_verify_viewer_font("${path}" "${sha256}" "${option}")
endfunction()

function(nuka_resolve_viewer_fonts)
    set(NUKA_VIEWER_INTER_REGULAR_FONT "" CACHE FILEPATH "Offline copy of the pinned Inter 4.1 Regular font")
    set(NUKA_VIEWER_INTER_SEMIBOLD_FONT "" CACHE FILEPATH "Offline copy of the pinned Inter 4.1 SemiBold font")
    set(NUKA_VIEWER_CJK_FONT "" CACHE FILEPATH "Offline copy of the pinned Noto Sans CJK SC font")
    set(regular_sha "40d692fce188e4471e2b3cba937be967878f631ad3ebbbdcd587687c7ebe0c82")
    set(semibold_sha "78a843fade9d4612a5567302fb595b56976eb5fcebf4fea5a5912d638bafcde3")
    set(cjk_sha "2c76254f6fc379fddfce0a7e84fb5385bb135d3e399294f6eeb6680d0365b74b")
    set(font_dir "${CMAKE_BINARY_DIR}/_deps/nuka-fonts")
    if(NUKA_VIEWER_CJK_FONT)
        nuka_verify_viewer_font("${NUKA_VIEWER_CJK_FONT}" "${cjk_sha}" "NUKA_VIEWER_CJK_FONT")
    endif()
    foreach(role IN ITEMS REGULAR SEMIBOLD)
        string(TOLOWER "${role}" lower_role)
        if(NUKA_VIEWER_INTER_${role}_FONT)
            nuka_verify_viewer_font("${NUKA_VIEWER_INTER_${role}_FONT}" "${${lower_role}_sha}" "NUKA_VIEWER_INTER_${role}_FONT")
        endif()
    endforeach()
    if(NOT NUKA_VIEWER_INTER_REGULAR_FONT OR NOT NUKA_VIEWER_INTER_SEMIBOLD_FONT)
        nuka_download_viewer_font(
            "https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip"
            "${font_dir}/Inter-4.1.zip"
            "9883fdd4a49d4fb66bd8177ba6625ef9a64aa45899767dde3d36aa425756b11e"
            "NUKA_VIEWER_INTER_REGULAR_FONT and NUKA_VIEWER_INTER_SEMIBOLD_FONT")
        file(ARCHIVE_EXTRACT INPUT "${font_dir}/Inter-4.1.zip" DESTINATION "${font_dir}/inter-4.1"
            PATTERNS "extras/ttf/Inter-Regular.ttf" "extras/ttf/Inter-SemiBold.ttf")
        if(NOT NUKA_VIEWER_INTER_REGULAR_FONT)
            set(NUKA_VIEWER_INTER_REGULAR_FONT "${font_dir}/inter-4.1/extras/ttf/Inter-Regular.ttf")
        endif()
        if(NOT NUKA_VIEWER_INTER_SEMIBOLD_FONT)
            set(NUKA_VIEWER_INTER_SEMIBOLD_FONT "${font_dir}/inter-4.1/extras/ttf/Inter-SemiBold.ttf")
        endif()
    endif()
    if(NOT NUKA_VIEWER_CJK_FONT)
        set(NUKA_VIEWER_CJK_FONT "${font_dir}/NotoSansCJKsc-Regular.otf")
        nuka_download_viewer_font(
            "https://raw.githubusercontent.com/notofonts/noto-cjk/f8d157532fbfaeda587e826d4cd5b21a49186f7c/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf"
            "${NUKA_VIEWER_CJK_FONT}" "${cjk_sha}" "NUKA_VIEWER_CJK_FONT")
    endif()
    nuka_verify_viewer_font("${NUKA_VIEWER_INTER_REGULAR_FONT}" "${regular_sha}" "NUKA_VIEWER_INTER_REGULAR_FONT")
    nuka_verify_viewer_font("${NUKA_VIEWER_INTER_SEMIBOLD_FONT}" "${semibold_sha}" "NUKA_VIEWER_INTER_SEMIBOLD_FONT")
    foreach(role IN ITEMS INTER_REGULAR INTER_SEMIBOLD CJK)
        set(NUKA_VIEWER_${role}_FONT "${NUKA_VIEWER_${role}_FONT}" PARENT_SCOPE)
    endforeach()
endfunction()
